name: publish
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: git config --global init.defaultBranch main
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.GH_TOKEN }}
          deploy-branch: gh-pages
          gatsby-args: --prefix-paths
          
          
