name: publish
on:
  push:
    branches:
      - master

jobs:
  build:     
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: enriikke/gatsby-gh-pages-action@v2
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          PREFIX_PATHS: true
        with:
          access-token: ${{ secrets.GH_TOKEN }}
          deploy-branch: gh-pages
          gatsby-args: --prefix-paths
          
          
